routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('pages.welcome');
})->name('welcome');

Route::get('public', function () {
  return view('auth.public');
})->name('public');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('dashboard', 'HomeController@index')->name('home');
Route::get('logs', 'HomeController@logs')->name('page.logs');
Route::get('pricing', 'ExamplePagesController@pricing')->name('page.pricing');
Route::get('lock', 'ExamplePagesController@lock')->name('page.lock');
Route::get('error', ['as' => 'page.error', 'uses' => 'ExamplePagesController@error']);

Route::group(['middleware' => 'auth'], function () {
    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('agency', 'AgencyController', ['except' => ['show']]);
    
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    
    Route::get('rtl-support', ['as' => 'page.rtl-support', 'uses' => 'ExamplePagesController@rtlSupport']);
    Route::get('timeline', ['as' => 'page.timeline', 'uses' => 'ExamplePagesController@timeline']);
    Route::get('widgets', ['as' => 'page.widgets', 'uses' => 'ExamplePagesController@widgets']);
    Route::get('charts', ['as' => 'page.charts', 'uses' => 'ExamplePagesController@charts']);
    Route::get('calendar', ['as' => 'page.calendar', 'uses' => 'ExamplePagesController@calendar']);

    Route::get('buttons', ['as' => 'page.buttons', 'uses' => 'ComponentPagesController@buttons']);
    Route::get('grid-system', ['as' => 'page.grid', 'uses' => 'ComponentPagesController@grid']);
    Route::get('panels', ['as' => 'page.panels', 'uses' => 'ComponentPagesController@panels']);
    Route::get('sweet-alert', ['as' => 'page.sweet-alert', 'uses' => 'ComponentPagesController@sweetAlert']);
    Route::get('notifications', ['as' => 'page.notifications', 'uses' => 'ComponentPagesController@notifications']);
    Route::get('icons', ['as' => 'page.icons', 'uses' => 'ComponentPagesController@icons']);
    Route::get('typography', ['as' => 'page.typography', 'uses' => 'ComponentPagesController@typography']);
    
    Route::get('regular-tables', ['as' => 'page.regular_tables', 'uses' => 'TablePagesController@regularTables']);
    Route::get('extended-tables', ['as' => 'page.extended_tables', 'uses' => 'TablePagesController@extendedTables']);
    Route::get('datatable-tables', ['as' => 'page.datatable_tables', 'uses' => 'TablePagesController@datatableTables']);

    Route::get('regular-form', ['as' => 'page.regular_forms', 'uses' => 'FormPagesController@regularForms']);
    Route::get('extended-form', ['as' => 'page.extended_forms', 'uses' => 'FormPagesController@extendedForms']);
    Route::get('validation-form', ['as' => 'page.validation_forms', 'uses' => 'FormPagesController@validationForms']);
    Route::get('wizard-form', ['as' => 'page.wizard_forms', 'uses' => 'FormPagesController@wizardForms']);

    Route::get('google-maps', ['as' => 'page.google_maps', 'uses' => 'MapPagesController@googleMaps']);
    Route::get('fullscreen-maps', ['as' => 'page.fullscreen_maps', 'uses' => 'MapPagesController@fullscreenMaps']);
    Route::get('vector-maps', ['as' => 'page.vector_maps', 'uses' => 'MapPagesController@vectorMaps']);

    Route::get('manual', ['as' => 'page.manual', 'uses' => 'HomeController@manual']);
    Route::get('usermanual', ['as' => 'page.usermanual', 'uses' => 'HomeController@usermanual']);
    //NEW
    Route::get('addproject', ['as' => 'page.addproject', 'uses' => 'AddProjectController@addproject']);
    Route::get('addpage', ['as' => 'page.addpage', 'uses' => 'AddProjectController@addpage']);
    Route::post('addpage', ['as' => 'page.addpage', 'uses' => 'AddProjectController@saveproject']);
    Route::get('editpage/{id}', ['as' => 'page.editpage', 'uses' => 'AddProjectController@editpage']);
    Route::post('editpage/{id}', ['as' => 'page.editpage', 'uses' => 'AddProjectController@editsave']);
    Route::get('reportgen', ['as' => 'page.reportgen', 'uses' => 'ReportGenController@reportgen']);
    Route::get('spatial', ['as' => 'page.spatial', 'uses' => 'AddProjectController@spatial']);
    Route::post('deleteproject/{id}', ['as' => 'page.deleteproject', 'uses' => 'AddProjectController@deleteproject']);
    //Form 1
    Route::get('form1agency', ['as' => 'page.form1agency', 'uses' => 'EFormsController@form1agency']);
    Route::post('form1agency_add/{id}', ['as' => 'page.form1agency_add', 'uses' => 'EFormsController@form1agency_add']);
    Route::get('editform1/{id}', ['as' => 'page.editform1', 'uses' => 'EFormsController@editform1']);
    Route::post('form1agency_projects_add/{id}', ['as' => 'page.form1agency_projects_add', 'uses' => 'EFormsController@form1agency_projects_add']);
    Route::post('endorse/{id}', ['as' => 'page.endorse', 'uses' => 'EFormsController@endorse']); 
    Route::post('form1agency_submit/{id}', ['as' => 'page.form1agency_submit', 'uses' => 'EFormsController@form1agency_submit']); 
    Route::post('form1agency_submitfs/{id}', ['as' => 'page.form1agency_submitfs', 'uses' => 'EFormsController@form1agency_submitfs']); 
    Route::post('form1agency_submitpt/{id}', ['as' => 'page.form1agency_submitpt', 'uses' => 'EFormsController@form1agency_submitpt']); 
    Route::post('form1agency_submitoi/{id}', ['as' => 'page.form1agency_submitoi', 'uses' => 'EFormsController@form1agency_submitoi']);
    Route::post('form1agency_submiteg/{id}', ['as' => 'page.form1agency_submiteg', 'uses' => 'EFormsController@form1agency_submiteg']); 
    Route::post('deleteprojectform1/{id}', ['as' => 'page.deleteprojectform1', 'uses' => 'EFormsController@deleteprojectform1']);
    Route::post('deleteprojectform2/{id}', ['as' => 'page.deleteprojectform2', 'uses' => 'EFormsController@deleteprojectform2']);
    Route::post('deleteprojectform3/{id}', ['as' => 'page.deleteprojectform3', 'uses' => 'EFormsController@deleteprojectform3']);
    Route::post('deleteprojectform4/{id}', ['as' => 'page.deleteprojectform4', 'uses' => 'EFormsController@deleteprojectform4']);
    Route::post('deleteprojectform5/{id}', ['as' => 'page.deleteprojectform5', 'uses' => 'EFormsController@deleteprojectform5']);
    Route::post('deleteprojectform6/{id}', ['as' => 'page.deleteprojectform6', 'uses' => 'EFormsController@deleteprojectform6']);
    //Form 1 MIMAROPA
    Route::get('form1', ['as' => 'page.form1', 'uses' => 'EFormsControllerAdmin@form1']);
    Route::post('addform1', ['as' => 'page.addform1', 'uses' => 'EFormsControllerAdmin@addform1']);
    Route::post('lockform1/{id}', ['as' => 'page.lockform1', 'uses' => 'EFormsControllerAdmin@lockform1']);
    Route::post('unlock/{id}', ['as' => 'page.unlock', 'uses' => 'EFormsControllerAdmin@unlock']);
    Route::get('form1submission/{id}', ['as' => 'page.form1submission', 'uses' => 'EFormsControllerAdmin@form1submission']);
    Route::get('form1submissionview/{id}', ['as' => 'page.form1submissionview', 'uses' => 'EFormsControllerAdmin@form1submissionview']);
    Route::post('review/{id}', ['as' => 'page.review', 'uses' => 'EFormsControllerAdmin@review']);
    Route::post('formreview/{id}', ['as' => 'page.formreview', 'uses' => 'EFormsControllerAdmin@formreview']);
    // Route::get('/addproject', 'AddProjectController@addproject')->name('addproject');
//SAMPLE PUSH TO LANCE
    //Form 2 MIMAROPA
    Route::get('form2', ['as' => 'page.form2', 'uses' => 'EFormsControllerAdmin@form2']);
    Route::post('addform2', ['as' => 'page.addform2', 'uses' => 'EFormsControllerAdmin@addform2']);
    Route::post('lockform2/{id}', ['as' => 'page.lockform2', 'uses' => 'EFormsControllerAdmin@lockform2']);
    Route::post('unlock2/{id}', ['as' => 'page.unlock2', 'uses' => 'EFormsControllerAdmin@unlock2']);
    Route::get('form2submission/{id}', ['as' => 'page.form2submission', 'uses' => 'EFormsControllerAdmin@form2submission']);
    Route::post('form2review/{id}', ['as' => 'page.form2review', 'uses' => 'EFormsControllerAdmin@form2review']);   
    Route::get('form2submissionview/{id}', ['as' => 'page.form2submissionview', 'uses' => 'EFormsControllerAdmin@form2submissionview']);
    Route::post('review2/{id}', ['as' => 'page.review2', 'uses' => 'EFormsControllerAdmin@review2']); 

    //Form 2 Agency
    Route::get('form2agency', ['as' => 'page.form2agency', 'uses' => 'EFormsController@form2agency']);
    Route::post('form2agency_add/{id}', ['as' => 'page.form2agency_add', 'uses' => 'EFormsController@form2agency_add']);
    Route::get('editform2/{id}', ['as' => 'page.editform2', 'uses' => 'EFormsController@editform2']);
    Route::post('form2agency_submit/{id}', ['as' => 'page.form2agency_submit', 'uses' => 'EFormsController@form2agency_submit']); 
    Route::post('form2agency_projects_add/{id}', ['as' => 'page.form2agency_projects_add', 'uses' => 'EFormsController@form2agency_projects_add']);
    Route::post('endorse2/{id}', ['as' => 'page.endorse2', 'uses' => 'EFormsController@endorse2']); 
    Route::post('form2agency_submitfs/{id}', ['as' => 'page.form2agency_submitfs', 'uses' => 'EFormsController@form2agency_submitfs']); 

app/Tag.php
<?php
/*

=========================================================
* Argon Dashboard PRO - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard-pro-laravel
* Copyright 2018 Creative Tim (https://www.creative-tim.com) & UPDIVISION (https://www.updivision.com)

* Coded by www.creative-tim.com & www.updivision.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
namespace App;

use App\Item;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'color'];

    /**
     * Get the items of the tag
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function items()
    {
        return $this->belongsToMany(Item::class);
    }
}

app/Http/Controllers/TagController.php
<?php
/*

=========================================================
* Argon Dashboard PRO - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard-pro-laravel
* Copyright 2018 Creative Tim (https://www.creative-tim.com) & UPDIVISION (https://www.updivision.com)

* Coded by www.creative-tim.com & www.updivision.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
namespace App\Http\Controllers;

use App\Tag;
use App\User;
use App\Http\Requests\TagRequest;

class TagController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Tag::class);
    }

    /**
     * Display a listing of the tags
     *
     * @param \App\Tag  $model
     * @return \Illuminate\View\View
     */
    public function index(Tag $model)
    {
        $this->authorize('manage-items', User::class);

        return view('tags.index', ['tags' => $model->all()]);
    }

    /**
     * Show the form for creating a new tag
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created tag in storage
     *
     * @param  \App\Http\Requests\TagRequest  $request
     * @param  \App\Tag  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TagRequest $request, Tag $model)
    {
        $model->create($request->all());

        return redirect()->route('tag.index')->withStatus(__('Tag successfully created.'));
    }

    /**
     * Show the form for editing the specified tag
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\View\View
     */
    public function edit(Tag  $tag)
    {
        return view('tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\TagRequest  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TagRequest $request, Tag $tag)
    {
        $tag->update($request->all());

        return redirect()->route('tag.index')->withStatus(__('Tag successfully updated.'));
    }

    /**
     * Remove the specified tag from storage
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Tag $tag)
    {
        if (!$tag->items->isEmpty()) {
            return redirect()->route('tag.index')->withErrors(__('This tag has items attached and can\'t be deleted.'));
        }

        $tag->delete();

        return redirect()->route('tag.index')->withStatus(__('Tag successfully deleted.'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app', ['activePage' => 'tag-management', 'menuParent' => 'laravel', 'titlePage' => __('Tag Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('tag.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">label</i>
                </div>
                <h4 class="card-title">{{ __('Add Tag') }}</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('tag.index') }}" class="btn btn-sm btn-rose">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'name'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Color') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('color') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('color') ? ' is-invalid' : '' }}" name="color" id="input-color" type="color" placeholder="{{ __('Color') }}" value="{{ old('color') }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'color'])
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app', ['activePage' => 'tag-management', 'menuParent' => 'laravel', 'titlePage' => __('Tag Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('tag.update', $tag) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">label</i>
                </div>
                <h4 class="card-title">{{ __('Edit Tag') }}</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('tag.index') }}" class="btn btn-sm btn-rose">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name', $tag->name) }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'name'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Color') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('color') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('color') ? ' is-invalid' : '' }}" name="color" id="input-color" type="color" placeholder="{{ __('Color') }}" value="{{ old('color', $tag->color) }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'color'])
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app', ['activePage' => 'tag-management', 'menuParent' => 'laravel', 'titlePage' => __('Tag Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">label</i>
                </div>
                <h4 class="card-title">{{ __('Tags') }}</h4>
              </div>
              <div class="card-body">
                @can('create', App\Tag::class)
                  <div class="row">
                    <div class="col-12 text-right">
                      <a href="{{ route('tag.create') }}" class="btn btn-sm btn-rose">{{ __('Add tag') }}</a>
                    </div>
                  </div>
                @endcan
                <div class="table-responsive">
                  <table id="datatables" class="table table-striped table-no-bordered table-hover" style="display:none">
                    <thead class="text-primary">
                      <th>
                          {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Color') }}
                      </th>
                      <th>
                        {{ __('Creation date') }}
                      </th>
                      @can('manage-items', App\User::class)
                        <th class="text-right">
                          {{ __('Actions') }}
                        </th>
                      @endcan
                    </thead>
                    <tbody>
                      @foreach($tags as $tag)
                        <tr>
                          <td>
                            {{ $tag->name }}
                          </td>
                          <td>
                            <span class="badge badge-default" style="background-color:{{ $tag->color }}">{{ $tag->name }}</span>
                          </td>
                          <td>
                            {{ $tag->created_at->format('Y-m-d') }}
                          </td>
                          @can('manage-items', App\User::class)
                            <td class="td-actions text-right">
                              <form action="{{ route('tag.destroy', $tag) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                @can('update', $tag)
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('tag.edit', $tag) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                @endcan
                                @if ($tag->items->isEmpty() && auth()->user()->can('delete', $tag))
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this tag?") }}') ? this.parentElement.submit() : ''">
                                      <i class="material-icons">close</i>
                                      <div class="ripple-container"></div>
                                  </button>
                                @endif
                              </form>
                            </td>
                          @endcan
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('js')
<script>
  $(document).ready(function() {
    $('#datatables').fadeIn(1100);
    $('#datatables').DataTable({
      "pagingType": "full_numbers",
      "lengthMenu": [
        [10, 25, 50, -1],
        [10, 25, 50, "All"]
      ],
      responsive: true,
      language: {
        search: "_INPUT_",
        searchPlaceholder: "Search tags",
      },
      "columnDefs": [
        { "orderable": false, "targets": 3 },
      ],
    });
  });
</script>
@endpush