routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('pages.welcome');
})->name('welcome');

Route::get('public', function () {
  return view('auth.public');
})->name('public');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('dashboard', 'HomeController@index')->name('home');
Route::get('logs', 'HomeController@logs')->name('page.logs');
Route::get('pricing', 'ExamplePagesController@pricing')->name('page.pricing');
Route::get('lock', 'ExamplePagesController@lock')->name('page.lock');
Route::get('error', ['as' => 'page.error', 'uses' => 'ExamplePagesController@error']);

Route::group(['middleware' => 'auth'], function () {
    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('agency', 'AgencyController', ['except' => ['show']]);
    
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    
    Route::get('rtl-support', ['as' => 'page.rtl-support', 'uses' => 'ExamplePagesController@rtlSupport']);
    Route::get('timeline', ['as' => 'page.timeline', 'uses' => 'ExamplePagesController@timeline']);
    Route::get('widgets', ['as' => 'page.widgets', 'uses' => 'ExamplePagesController@widgets']);
    Route::get('charts', ['as' => 'page.charts', 'uses' => 'ExamplePagesController@charts']);
    Route::get('calendar', ['as' => 'page.calendar', 'uses' => 'ExamplePagesController@calendar']);

    Route::get('buttons', ['as' => 'page.buttons', 'uses' => 'ComponentPagesController@buttons']);
    Route::get('grid-system', ['as' => 'page.grid', 'uses' => 'ComponentPagesController@grid']);
    Route::get('panels', ['as' => 'page.panels', 'uses' => 'ComponentPagesController@panels']);
    Route::get('sweet-alert', ['as' => 'page.sweet-alert', 'uses' => 'ComponentPagesController@sweetAlert']);
    Route::get('notifications', ['as' => 'page.notifications', 'uses' => 'ComponentPagesController@notifications']);
    Route::get('icons', ['as' => 'page.icons', 'uses' => 'ComponentPagesController@icons']);
    Route::get('typography', ['as' => 'page.typography', 'uses' => 'ComponentPagesController@typography']);
    
    Route::get('regular-tables', ['as' => 'page.regular_tables', 'uses' => 'TablePagesController@regularTables']);
    Route::get('extended-tables', ['as' => 'page.extended_tables', 'uses' => 'TablePagesController@extendedTables']);
    Route::get('datatable-tables', ['as' => 'page.datatable_tables', 'uses' => 'TablePagesController@datatableTables']);

    Route::get('regular-form', ['as' => 'page.regular_forms', 'uses' => 'FormPagesController@regularForms']);
    Route::get('extended-form', ['as' => 'page.extended_forms', 'uses' => 'FormPagesController@extendedForms']);
    Route::get('validation-form', ['as' => 'page.validation_forms', 'uses' => 'FormPagesController@validationForms']);
    Route::get('wizard-form', ['as' => 'page.wizard_forms', 'uses' => 'FormPagesController@wizardForms']);

    Route::get('google-maps', ['as' => 'page.google_maps', 'uses' => 'MapPagesController@googleMaps']);
    Route::get('fullscreen-maps', ['as' => 'page.fullscreen_maps', 'uses' => 'MapPagesController@fullscreenMaps']);
    Route::get('vector-maps', ['as' => 'page.vector_maps', 'uses' => 'MapPagesController@vectorMaps']);

    Route::get('manual', ['as' => 'page.manual', 'uses' => 'HomeController@manual']);
    Route::get('usermanual', ['as' => 'page.usermanual', 'uses' => 'HomeController@usermanual']);
    //NEW
    Route::get('addproject', ['as' => 'page.addproject', 'uses' => 'AddProjectController@addproject']);
    Route::get('addpage', ['as' => 'page.addpage', 'uses' => 'AddProjectController@addpage']);
    Route::post('addpage', ['as' => 'page.addpage', 'uses' => 'AddProjectController@saveproject']);
    Route::get('editpage/{id}', ['as' => 'page.editpage', 'uses' => 'AddProjectController@editpage']);
    Route::post('editpage/{id}', ['as' => 'page.editpage', 'uses' => 'AddProjectController@editsave']);
    Route::get('reportgen', ['as' => 'page.reportgen', 'uses' => 'ReportGenController@reportgen']);
    Route::get('spatial', ['as' => 'page.spatial', 'uses' => 'AddProjectController@spatial']);
    Route::post('deleteproject/{id}', ['as' => 'page.deleteproject', 'uses' => 'AddProjectController@deleteproject']);
    //Form 1
    Route::get('form1agency', ['as' => 'page.form1agency', 'uses' => 'EFormsController@form1agency']);
    Route::post('form1agency_add/{id}', ['as' => 'page.form1agency_add', 'uses' => 'EFormsController@form1agency_add']);
    Route::get('editform1/{id}', ['as' => 'page.editform1', 'uses' => 'EFormsController@editform1']);
    Route::post('form1agency_projects_add/{id}', ['as' => 'page.form1agency_projects_add', 'uses' => 'EFormsController@form1agency_projects_add']);
    Route::post('endorse/{id}', ['as' => 'page.endorse', 'uses' => 'EFormsController@endorse']); 
    Route::post('form1agency_submit/{id}', ['as' => 'page.form1agency_submit', 'uses' => 'EFormsController@form1agency_submit']); 
    Route::post('form1agency_submitfs/{id}', ['as' => 'page.form1agency_submitfs', 'uses' => 'EFormsController@form1agency_submitfs']); 
    Route::post('form1agency_submitpt/{id}', ['as' => 'page.form1agency_submitpt', 'uses' => 'EFormsController@form1agency_submitpt']); 
    Route::post('form1agency_submitoi/{id}', ['as' => 'page.form1agency_submitoi', 'uses' => 'EFormsController@form1agency_submitoi']);
    Route::post('form1agency_submiteg/{id}', ['as' => 'page.form1agency_submiteg', 'uses' => 'EFormsController@form1agency_submiteg']); 
    Route::post('deleteprojectform1/{id}', ['as' => 'page.deleteprojectform1', 'uses' => 'EFormsController@deleteprojectform1']);
    Route::post('deleteprojectform2/{id}', ['as' => 'page.deleteprojectform2', 'uses' => 'EFormsController@deleteprojectform2']);
    Route::post('deleteprojectform3/{id}', ['as' => 'page.deleteprojectform3', 'uses' => 'EFormsController@deleteprojectform3']);
    Route::post('deleteprojectform4/{id}', ['as' => 'page.deleteprojectform4', 'uses' => 'EFormsController@deleteprojectform4']);
    Route::post('deleteprojectform5/{id}', ['as' => 'page.deleteprojectform5', 'uses' => 'EFormsController@deleteprojectform5']);
    Route::post('deleteprojectform6/{id}', ['as' => 'page.deleteprojectform6', 'uses' => 'EFormsController@deleteprojectform6']);
    //Form 1 MIMAROPA
    Route::get('form1', ['as' => 'page.form1', 'uses' => 'EFormsControllerAdmin@form1']);
    Route::post('addform1', ['as' => 'page.addform1', 'uses' => 'EFormsControllerAdmin@addform1']);
    Route::post('lockform1/{id}', ['as' => 'page.lockform1', 'uses' => 'EFormsControllerAdmin@lockform1']);
    Route::post('unlock/{id}', ['as' => 'page.unlock', 'uses' => 'EFormsControllerAdmin@unlock']);
    Route::get('form1submission/{id}', ['as' => 'page.form1submission', 'uses' => 'EFormsControllerAdmin@form1submission']);
    Route::get('form1submissionview/{id}', ['as' => 'page.form1submissionview', 'uses' => 'EFormsControllerAdmin@form1submissionview']);
    Route::post('review/{id}', ['as' => 'page.review', 'uses' => 'EFormsControllerAdmin@review']);
    Route::post('formreview/{id}', ['as' => 'page.formreview', 'uses' => 'EFormsControllerAdmin@formreview']);
    // Route::get('/addproject', 'AddProjectController@addproject')->name('addproject');
//SAMPLE PUSH TO LANCE
    //Form 2 MIMAROPA
    Route::get('form2', ['as' => 'page.form2', 'uses' => 'EFormsControllerAdmin@form2']);
    Route::post('addform2', ['as' => 'page.addform2', 'uses' => 'EFormsControllerAdmin@addform2']);
    Route::post('lockform2/{id}', ['as' => 'page.lockform2', 'uses' => 'EFormsControllerAdmin@lockform2']);
    Route::post('unlock2/{id}', ['as' => 'page.unlock2', 'uses' => 'EFormsControllerAdmin@unlock2']);
    Route::get('form2submission/{id}', ['as' => 'page.form2submission', 'uses' => 'EFormsControllerAdmin@form2submission']);
    Route::post('form2review/{id}', ['as' => 'page.form2review', 'uses' => 'EFormsControllerAdmin@form2review']);   
    Route::get('form2submissionview/{id}', ['as' => 'page.form2submissionview', 'uses' => 'EFormsControllerAdmin@form2submissionview']);
    Route::post('review2/{id}', ['as' => 'page.review2', 'uses' => 'EFormsControllerAdmin@review2']); 

    //Form 2 Agency
    Route::get('form2agency', ['as' => 'page.form2agency', 'uses' => 'EFormsController@form2agency']);
    Route::post('form2agency_add/{id}', ['as' => 'page.form2agency_add', 'uses' => 'EFormsController@form2agency_add']);
    Route::get('editform2/{id}', ['as' => 'page.editform2', 'uses' => 'EFormsController@editform2']);
    Route::post('form2agency_submit/{id}', ['as' => 'page.form2agency_submit', 'uses' => 'EFormsController@form2agency_submit']); 
    Route::post('form2agency_projects_add/{id}', ['as' => 'page.form2agency_projects_add', 'uses' => 'EFormsController@form2agency_projects_add']);
    Route::post('endorse2/{id}', ['as' => 'page.endorse2', 'uses' => 'EFormsController@endorse2']); 
    Route::post('form2agency_submitfs/{id}', ['as' => 'page.form2agency_submitfs', 'uses' => 'EFormsController@form2agency_submitfs']); 

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="azure" data-background-color="black" data-image="{{ asset('material') }}/img/mimaropa.jpg">
  <!--
    Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

    Tip 2: you can also add an image using data-image tag
-->
  <div class="logo">
    <a href="https://www.neda.gov.ph/" class="simple-text logo-mini">
      <img class="img" src="{{ asset('material')}}/img/neda-logo.png" height="30">
    </a>
    <a href="https://www.neda.gov.ph/" class="simple-text logo-normal">
      {{ __('ProyekTanglaw') }}
    </a>
  </div>
  <div class="sidebar-wrapper">
    <div class="user">
      <div class="photo">
        <img src="{{ auth()->user()->profilePicture() }}" />
      </div>
      <div class="user-info">
        <a data-toggle="collapse" href="#collapseExample" class="username">
          <span>
            {{ auth()->user()->name }}
            <b class="caret"></b>
          </span>
        </a>
        <div class="collapse" id="collapseExample">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link" href="{{ route('profile.edit') }}">
                <span class="sidebar-mini"> MP </span>
                <span class="sidebar-normal"> My Profile </span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <ul class="nav">
      <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
          <i class="material-icons">dashboard</i>
            <p>{{ __('Dashboard') }}</p>
        </a>
      </li>
      @if(auth()->user()->role_id == 1)
      <li class="nav-item {{ ($menuParent == 'laravel' || $activePage == 'dashboard') ? ' active' : '' }}">
        <a class="nav-link" data-toggle="collapse" href="#laravelExample" {{ ($menuParent == 'laravel' || $activePage == 'dashboard') ? ' aria-expanded="true"' : '' }}>
          <i><img style="width:25px" src="{{ asset('material') }}/img/laravel.svg"></i>
          <p>{{ __('Administration') }}
            <b class="caret"></b>
          </p>
        </a>
        <div class="collapse {{ ($menuParent == 'dashboard' || $menuParent == 'laravel') ? ' show' : '' }}" id="laravelExample">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('profile.edit') }}">
                <span class="sidebar-mini"> UP </span>
                <span class="sidebar-normal">{{ __('User profile') }} </span>
              </a>
            </li>
            @can('manage-users', App\User::class)
              <li class="nav-item{{ $activePage == 'role-management' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('role.index') }}">
                  <span class="sidebar-mini"> RM </span>
                  <span class="sidebar-normal"> {{ __('Role Management') }} </span>
                </a>
              </li>
            @endcan
            @can('manage-users', App\User::class)
              <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('user.index') }}">
                  <span class="sidebar-mini"> UM </span>
                  <span class="sidebar-normal"> {{ __('User Management') }} </span>
                </a>
              </li>
            @endcan
            @can('manage-users', App\User::class)
              <li class="nav-item{{ $activePage == 'agency-management' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('agency.index') }}">
                  <span class="sidebar-mini"> AM </span>
                  <span class="sidebar-normal"> {{ __('Agency Management') }} </span>
                </a>
              </li>
            @endcan
            @can('manage-users', App\User::class)
              <li class="nav-item{{ $activePage == 'logs' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('page.logs') }}">
                  <span class="sidebar-mini"> SL </span>
                  <span class="sidebar-normal"> {{ __('System Logs') }} </span>
                </a>
              </li>
            @endcan
          </ul>
        </div>
      </li>
      @endif
      <li class="nav-item{{ $activePage == 'addproject' ? ' active' : '' }} ">
        <a class="nav-link" href="{{ route('page.addproject') }}">
          <i class="material-icons">storage</i>
          <p> Projects </p>
        </a>
      </li>
      <li class="nav-item {{ $menuParent == 'forms' ? ' active' : '' }}">
        <a class="nav-link" data-toggle="collapse" href="#formsExamples" {{ $menuParent == 'forms' ? 'aria-expanded="true"' : '' }}>
          <i class="material-icons">content_paste</i>
          <p> eRPMES
            <b class="caret"></b>
          </p>
        </a>
        @if(auth()->user()->role_id == 1 || auth()->user()->role_id == 3)
        <div class="collapse {{ $menuParent == 'forms' ? 'show' : '' }}" id="formsExamples">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'form1' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form1') }}">
                <span class="sidebar-mini"> 1 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 1') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form2' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form2') }}">
                <span class="sidebar-mini"> 2 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 2') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form3' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form3') }}">
                <span class="sidebar-mini"> 3 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 3') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form4' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form4') }}">
                <span class="sidebar-mini"> 4 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 4') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form5' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form5') }}">
                <span class="sidebar-mini"> 5 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 5') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form6' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form6') }}">
                <span class="sidebar-mini"> 6 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 6') }} </span>
              </a>
            </li>
          </ul>
        </div>
        @elseif(auth()->user()->role_id == 2)
        <div class="collapse {{ $menuParent == 'forms' ? 'show' : '' }}" id="formsExamples">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'form1agency' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form1agency') }}">
                <span class="sidebar-mini"> 1 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 1') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form2agency' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form2agency') }}">
                <span class="sidebar-mini"> 2 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 2') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form3agency' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form3agency') }}">
                <span class="sidebar-mini"> 3 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 3') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'form4agency' ? ' active' : '' }} ">
              <a class="nav-link" href="{{ route('page.form4agency') }}">
                <span class="sidebar-mini"> 4 </span>
                <span class="sidebar-normal"> {{ __('RPMES Form 4') }} </span>
              </a>
            </li>
          </ul>
        </div>
        @endif
      </li>
      @if(auth()->user()->agency_id == 47 || auth()->user()->agency_id == 48 || auth()->user()->agency_id == 49 || auth()->user()->agency_id == 50 || auth()->user()->agency_id == 51)
          <li class="nav-item{{ $activePage == 'spatial' ? ' active' : '' }} ">
            <a class="nav-link" href="{{ route('page.spatial') }}">
              <i class="material-icons">storage</i>
              <p> Spatial Projects </p>
            </a>
          </li>
      @endif
      <li class="nav-item{{ $activePage == 'reportgen' ? ' active' : '' }} ">
        <a class="nav-link" href="{{ route('page.reportgen') }}">
          <i class="material-icons">insert_chart</i>
          <p> Report Generation </p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'about' ? ' active' : '' }} ">
        <a class="nav-link" href="{{ route('page.about') }}">
          <i class="material-icons">remove_red_eye</i>
          <p> About ProyekTanglaw </p>
        </a>
      </li>
    </ul>
  </div>
</div>