routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('pages.welcome');
})->name('welcome');

Route::get('public', function () {
  return view('auth.public');
})->name('public');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('dashboard', 'HomeController@index')->name('home');
Route::get('logs', 'HomeController@logs')->name('page.logs');
Route::get('pricing', 'ExamplePagesController@pricing')->name('page.pricing');
Route::get('lock', 'ExamplePagesController@lock')->name('page.lock');
Route::get('error', ['as' => 'page.error', 'uses' => 'ExamplePagesController@error']);

Route::group(['middleware' => 'auth'], function () {
    Route::resource('category', 'CategoryController', ['except' => ['show']]);
    Route::resource('tag', 'TagController', ['except' => ['show']]);
    Route::resource('item', 'ItemController', ['except' => ['show']]);
    Route::resource('role', 'RoleController', ['except' => ['show', 'destroy']]);
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::resource('agency', 'AgencyController', ['except' => ['show']]);
    
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    
    Route::get('rtl-support', ['as' => 'page.rtl-support', 'uses' => 'ExamplePagesController@rtlSupport']);
    Route::get('timeline', ['as' => 'page.timeline', 'uses' => 'ExamplePagesController@timeline']);
    Route::get('widgets', ['as' => 'page.widgets', 'uses' => 'ExamplePagesController@widgets']);
    Route::get('charts', ['as' => 'page.charts', 'uses' => 'ExamplePagesController@charts']);
    Route::get('calendar', ['as' => 'page.calendar', 'uses' => 'ExamplePagesController@calendar']);

    Route::get('buttons', ['as' => 'page.buttons', 'uses' => 'ComponentPagesController@buttons']);
    Route::get('grid-system', ['as' => 'page.grid', 'uses' => 'ComponentPagesController@grid']);
    Route::get('panels', ['as' => 'page.panels', 'uses' => 'ComponentPagesController@panels']);
    Route::get('sweet-alert', ['as' => 'page.sweet-alert', 'uses' => 'ComponentPagesController@sweetAlert']);
    Route::get('notifications', ['as' => 'page.notifications', 'uses' => 'ComponentPagesController@notifications']);
    Route::get('icons', ['as' => 'page.icons', 'uses' => 'ComponentPagesController@icons']);
    Route::get('typography', ['as' => 'page.typography', 'uses' => 'ComponentPagesController@typography']);
    
    Route::get('regular-tables', ['as' => 'page.regular_tables', 'uses' => 'TablePagesController@regularTables']);
    Route::get('extended-tables', ['as' => 'page.extended_tables', 'uses' => 'TablePagesController@extendedTables']);
    Route::get('datatable-tables', ['as' => 'page.datatable_tables', 'uses' => 'TablePagesController@datatableTables']);

    Route::get('regular-form', ['as' => 'page.regular_forms', 'uses' => 'FormPagesController@regularForms']);
    Route::get('extended-form', ['as' => 'page.extended_forms', 'uses' => 'FormPagesController@extendedForms']);
    Route::get('validation-form', ['as' => 'page.validation_forms', 'uses' => 'FormPagesController@validationForms']);
    Route::get('wizard-form', ['as' => 'page.wizard_forms', 'uses' => 'FormPagesController@wizardForms']);

    Route::get('google-maps', ['as' => 'page.google_maps', 'uses' => 'MapPagesController@googleMaps']);
    Route::get('fullscreen-maps', ['as' => 'page.fullscreen_maps', 'uses' => 'MapPagesController@fullscreenMaps']);
    Route::get('vector-maps', ['as' => 'page.vector_maps', 'uses' => 'MapPagesController@vectorMaps']);

    Route::get('manual', ['as' => 'page.manual', 'uses' => 'HomeController@manual']);
    Route::get('usermanual', ['as' => 'page.usermanual', 'uses' => 'HomeController@usermanual']);
    //NEW
    Route::get('addproject', ['as' => 'page.addproject', 'uses' => 'AddProjectController@addproject']);
    Route::get('addpage', ['as' => 'page.addpage', 'uses' => 'AddProjectController@addpage']);
    Route::post('addpage', ['as' => 'page.addpage', 'uses' => 'AddProjectController@saveproject']);
    Route::get('editpage/{id}', ['as' => 'page.editpage', 'uses' => 'AddProjectController@editpage']);
    Route::post('editpage/{id}', ['as' => 'page.editpage', 'uses' => 'AddProjectController@editsave']);
    Route::get('reportgen', ['as' => 'page.reportgen', 'uses' => 'ReportGenController@reportgen']);
    Route::get('spatial', ['as' => 'page.spatial', 'uses' => 'AddProjectController@spatial']);
    Route::post('deleteproject/{id}', ['as' => 'page.deleteproject', 'uses' => 'AddProjectController@deleteproject']);
    //Form 1
    Route::get('form1agency', ['as' => 'page.form1agency', 'uses' => 'EFormsController@form1agency']);
    Route::post('form1agency_add/{id}', ['as' => 'page.form1agency_add', 'uses' => 'EFormsController@form1agency_add']);
    Route::get('editform1/{id}', ['as' => 'page.editform1', 'uses' => 'EFormsController@editform1']);
    Route::post('form1agency_projects_add/{id}', ['as' => 'page.form1agency_projects_add', 'uses' => 'EFormsController@form1agency_projects_add']);
    Route::post('endorse/{id}', ['as' => 'page.endorse', 'uses' => 'EFormsController@endorse']); 
    Route::post('form1agency_submit/{id}', ['as' => 'page.form1agency_submit', 'uses' => 'EFormsController@form1agency_submit']); 
    Route::post('form1agency_submitfs/{id}', ['as' => 'page.form1agency_submitfs', 'uses' => 'EFormsController@form1agency_submitfs']); 
    Route::post('form1agency_submitpt/{id}', ['as' => 'page.form1agency_submitpt', 'uses' => 'EFormsController@form1agency_submitpt']); 
    Route::post('form1agency_submitoi/{id}', ['as' => 'page.form1agency_submitoi', 'uses' => 'EFormsController@form1agency_submitoi']);
    Route::post('form1agency_submiteg/{id}', ['as' => 'page.form1agency_submiteg', 'uses' => 'EFormsController@form1agency_submiteg']); 
    Route::post('deleteprojectform1/{id}', ['as' => 'page.deleteprojectform1', 'uses' => 'EFormsController@deleteprojectform1']);
    Route::post('deleteprojectform2/{id}', ['as' => 'page.deleteprojectform2', 'uses' => 'EFormsController@deleteprojectform2']);
    Route::post('deleteprojectform3/{id}', ['as' => 'page.deleteprojectform3', 'uses' => 'EFormsController@deleteprojectform3']);
    Route::post('deleteprojectform4/{id}', ['as' => 'page.deleteprojectform4', 'uses' => 'EFormsController@deleteprojectform4']);
    Route::post('deleteprojectform5/{id}', ['as' => 'page.deleteprojectform5', 'uses' => 'EFormsController@deleteprojectform5']);
    Route::post('deleteprojectform6/{id}', ['as' => 'page.deleteprojectform6', 'uses' => 'EFormsController@deleteprojectform6']);
    //Form 1 MIMAROPA
    Route::get('form1', ['as' => 'page.form1', 'uses' => 'EFormsControllerAdmin@form1']);
    Route::post('addform1', ['as' => 'page.addform1', 'uses' => 'EFormsControllerAdmin@addform1']);
    Route::post('lockform1/{id}', ['as' => 'page.lockform1', 'uses' => 'EFormsControllerAdmin@lockform1']);
    Route::post('unlock/{id}', ['as' => 'page.unlock', 'uses' => 'EFormsControllerAdmin@unlock']);
    Route::get('form1submission/{id}', ['as' => 'page.form1submission', 'uses' => 'EFormsControllerAdmin@form1submission']);
    Route::get('form1submissionview/{id}', ['as' => 'page.form1submissionview', 'uses' => 'EFormsControllerAdmin@form1submissionview']);
    Route::post('review/{id}', ['as' => 'page.review', 'uses' => 'EFormsControllerAdmin@review']);
    Route::post('formreview/{id}', ['as' => 'page.formreview', 'uses' => 'EFormsControllerAdmin@formreview']);
    // Route::get('/addproject', 'AddProjectController@addproject')->name('addproject');
//SAMPLE PUSH TO LANCE
    //Form 2 MIMAROPA
    Route::get('form2', ['as' => 'page.form2', 'uses' => 'EFormsControllerAdmin@form2']);
    Route::post('addform2', ['as' => 'page.addform2', 'uses' => 'EFormsControllerAdmin@addform2']);
    Route::post('lockform2/{id}', ['as' => 'page.lockform2', 'uses' => 'EFormsControllerAdmin@lockform2']);
    Route::post('unlock2/{id}', ['as' => 'page.unlock2', 'uses' => 'EFormsControllerAdmin@unlock2']);
    Route::get('form2submission/{id}', ['as' => 'page.form2submission', 'uses' => 'EFormsControllerAdmin@form2submission']);
    Route::post('form2review/{id}', ['as' => 'page.form2review', 'uses' => 'EFormsControllerAdmin@form2review']);   
    Route::get('form2submissionview/{id}', ['as' => 'page.form2submissionview', 'uses' => 'EFormsControllerAdmin@form2submissionview']);
    Route::post('review2/{id}', ['as' => 'page.review2', 'uses' => 'EFormsControllerAdmin@review2']); 

    //Form 2 Agency
    Route::get('form2agency', ['as' => 'page.form2agency', 'uses' => 'EFormsController@form2agency']);
    Route::post('form2agency_add/{id}', ['as' => 'page.form2agency_add', 'uses' => 'EFormsController@form2agency_add']);
    Route::get('editform2/{id}', ['as' => 'page.editform2', 'uses' => 'EFormsController@editform2']);
    Route::post('form2agency_submit/{id}', ['as' => 'page.form2agency_submit', 'uses' => 'EFormsController@form2agency_submit']); 
    Route::post('form2agency_projects_add/{id}', ['as' => 'page.form2agency_projects_add', 'uses' => 'EFormsController@form2agency_projects_add']);
    Route::post('endorse2/{id}', ['as' => 'page.endorse2', 'uses' => 'EFormsController@endorse2']); 
    Route::post('form2agency_submitfs/{id}', ['as' => 'page.form2agency_submitfs', 'uses' => 'EFormsController@form2agency_submitfs']); 

app/Item.php
<?php
/*

=========================================================
* Argon Dashboard PRO - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard-pro-laravel
* Copyright 2018 Creative Tim (https://www.creative-tim.com) & UPDIVISION (https://www.updivision.com)

* Coded by www.creative-tim.com & www.updivision.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
namespace App;

use App\Tag;
use App\Category;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'picture', 'category_id', 'status', 'date', 'show_on_homepage', 'options'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'options' => 'array',
    ];

    /**
     * Get the category of the item
     *
     * @return \App\Category
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the tags of the item
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Get the path to the picture
     *
     * @return string
     */
    public function path()
    {
        return "/storage/{$this->picture}";
    }
}

app/Http/Controllers/ItemController.php
<?php
/*

=========================================================
* Argon Dashboard PRO - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard-pro-laravel
* Copyright 2018 Creative Tim (https://www.creative-tim.com) & UPDIVISION (https://www.updivision.com)

* Coded by www.creative-tim.com & www.updivision.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
namespace App\Http\Controllers;

use App\Tag;
use App\Item;
use App\Category;
use Carbon\Carbon;
use App\Http\Requests\ItemRequest;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Item::class);
    }

    /**
     * Display a listing of the items
     *
     * @param \App\Item  $model
     * @return \Illuminate\View\View
     */
    public function index(Item $model)
    {
        return view('items.index', ['items' => $model->with(['tags', 'category'])->get()]);
    }

    /**
     * Show the form for creating a new item
     *
     * @param  \App\Tag $tagModel
     * @param  \App\Category $categoryModel
     * @return \Illuminate\View\View
     */
    public function create(Tag $tagModel, Category $categoryModel)
    {
        return view('items.create', [
            'tags' => $tagModel->get(['id', 'name']),
            'categories' => $categoryModel->get(['id', 'name'])
        ]);
    }

    /**
     * Store a newly created item in storage
     *
     * @param  \App\Http\Requests\ItemRequest  $request
     * @param  \App\Item  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ItemRequest $request, Item $model)
    {
        $item = $model->create($request->merge([
            'picture' => $request->photo->store('pictures', 'public'),
            'show_on_homepage' => $request->show_on_homepage ? 1 : 0,
            'options' => $request->options ? $request->options : null,
            'date' => $request->date ? Carbon::parse($request->date)->format('Y-m-d') : null
        ])->all());
        $item->tags()->sync($request->get('tags'));

        return redirect()->route('item.index')->withStatus(__('Item successfully created.'));
    }

    /**
     * Show the form for editing the specified item
     *
     * @param  \App\Item  $item
     * @param  \App\Tag   $tagModel
     * @param  \App\Category $categoryModel
     * @return \Illuminate\View\View
     */
    public function edit(Item $item, Tag $tagModel, Category $categoryModel)
    {
        return view('items.edit', [
            'item' => $item->load('tags'),
            'tags' => $tagModel->get(['id', 'name']),
            'categories' => $categoryModel->get(['id', 'name'])
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Itemuest  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ItemRequest $request, Item $item)
    {
        $item->update(
            $request->merge([
                'picture' => $request->photo ? $request->photo->store('pictures', 'public') : null,
                'show_on_homepage' => $request->show_on_homepage ? 1 : 0,
                'options' => $request->options ? $request->options : null,
                'date' => $request->date ? Carbon::parse($request->date)->format('Y-m-d') : null
            ])->except([$request->hasFile('photo') ? '' : 'picture'])
        );

        $item->tags()->sync($request->get('tags'));

        return redirect()->route('item.index')->withStatus(__('Item successfully updated.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Item $item)
    {
        $item->delete();

        return redirect()->route('item.index')->withStatus(__('Item successfully deleted.'));
    }
}

resources/views/items/create.blade.php
@extends('layouts.app', ['activePage' => 'item-management', 'menuParent' => 'laravel', 'titlePage' => __('Item Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" enctype="multipart/form-data" action="{{ route('item.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')
            <div class="card ">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">filter_none</i>
                </div>
                <h4 class="card-title">{{ __('Add Item') }}</h4>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('item.index') }}" class="btn btn-sm btn-rose">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Picture') }}</label>
                  <div class="col-sm-7">
                    <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                      <div class="fileinput-new thumbnail">
                        <img src="{{ asset('material') }}/img/image_placeholder.jpg" alt="...">
                      </div>
                      <div class="fileinput-preview fileinput-exists thumbnail"></div>
                      <div>
                        <span class="btn btn-rose btn-file">
                          <span class="fileinput-new">{{ __('Select image') }}</span>
                          <span class="fileinput-exists">{{ __('Change') }}</span>
                          <input type="file" name="photo" id = "input-picture" />
                        </span>
                          <a href="#pablo" class="btn btn-danger fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> {{ __('Remove') }}</a>
                      </div>
                      @include('alerts.feedback', ['field' => 'photo'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @include('alerts.feedback', ['field' => 'name'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Category') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('category_id') ? ' has-danger' : '' }}">
                        <select class="selectpicker col-sm-12 pl-0 pr-0" name="category_id" data-style="select-with-transition" title="" data-size="100">
                        <option value="">-</option>
                        @foreach ($categories as $category)
                        <option value="{{ $category->id }}" {{ $category->id == old('category_id') ? 'selected' : '' }}>{{ $category->name }}</option>
                        @endforeach
                      </select>
                      @include('alerts.feedback', ['field' => 'category_id'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Description') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                      <textarea name="description" id="input-description" cols="30" rows="10" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" placeholder="{{ __('Description') }}" value="{{ old('description') }}">{{ old('description') }}</textarea>
                      @include('alerts.feedback', ['field' => 'description'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Tags') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                        <select class="selectpicker col-sm-12 pl-0 pr-0" name="tags[]" data-style="select-with-transition" multiple title="-" data-size="7">
                            @foreach ($tags as $tag)
                              <option value="{{ $tag->id }}" {{ in_array($tag->id, old('tags') ?? []) ? 'selected' : '' }}>{{ $tag->name }}</option>
                            @endforeach
                        </select>
                      @include('alerts.feedback', ['field' => 'tags'])
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label label-checkbox">{{ __('Status') }}</label>
                  <div class="col-sm-10 checkbox-radios">
                    @foreach (config('items.statuses') as $value => $status)
                      <div class="form-check">
                        <label class="form-check-label">
                          <input name="status" class="form-check-input" id="{{ $value }}" value="{{ $value }}" type="radio" {{ old('status') == $value ? ' checked' : '' }}> {{ $status }}
                          <span class="circle">
                            <span class="check"></span>
                          </span>
                        </label>
                      </div>
                    @endforeach
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label label-checkbox">{{ __('Show on homepage') }}</label>
                  <div class="col-sm-10 checkbox-radios">
                    <div class="togglebutton">
                      <label>
                        <input type="checkbox" name="show_on_homepage" value="1" {{ old('show_on_homepage') == 1 ? ' checked' : '' }}>
                        <span class="toggle"></span>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label label-checkbox">{{ __('Options') }}</label>
                  <div class="col-sm-10 checkbox-radios">
                    @foreach (config('items.options') as $key => $option)
                      <div class="form-check">
                        <label class="form-check-label">
                          <input name="options[]" class="form-check-input" id="option-{{ $key }}" value="{{ $key }}" type="checkbox" {{ old('options') && in_array($key, old('options')) ? ' checked' : '' }}> {{ $option }}
                          <span class="form-check-sign">
                            <span class="check"></span>
                          </span>
                        </label>
                      </div>
                    @endforeach
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Date') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('date') ? ' has-danger' : '' }}">
                      <input type="text"  name="date" id="date"
                      placeholder="{{ __('Select date') }}" class="form-control datetimepicker" value="{{ old('date', now()->format('d-m-Y')) }}"/>
                      @include('alerts.feedback', ['field' => 'date'])
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose">{{ __('Add Item') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('js')
<script>
  $(document).ready(function() {
    $('.datetimepicker').datetimepicker({
      icons: {
          time: "fa fa-clock-o",
          date: "fa fa-calendar",
          up: "fa fa-chevron-up",
          down: "fa fa-chevron-down",
          previous: 'fa fa-chevron-left',
          next: 'fa fa-chevron-right',
          today: 'fa fa-screenshot',
          clear: 'fa fa-trash',
          close: 'fa fa-remove'
      },
      format: 'DD-MM-YYYY'
    });
  });
</script>
@endpush

resources/views/items/index.blade.php
@extends('layouts.app', ['activePage' => 'item-management', 'menuParent' => 'laravel', 'titlePage' => __('Item Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                  <i class="material-icons">filter_none</i>
                </div>
                <h4 class="card-title">{{ __('Items') }}</h4>
              </div>
              <div class="card-body">
                @can('create', App\Item::class)
                  <div class="row">
                    <div class="col-12 text-right">
                      <a href="{{ route('item.create') }}" class="btn btn-sm btn-rose">{{ __('Add Item') }}</a>
                    </div>
                  </div>
                @endcan
                <div class="table-responsive">
                  <table id="datatables" class="table table-striped table-no-bordered table-hover" style="display:none">
                    <thead class="text-primary">
                      <th>
                          {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Category') }}
                      </th>
                      <th>
                        {{ __('Picture') }}
                      </th>
                      <th>
                        {{ __('Tags') }}
                      </th>
                      <th>
                        {{ __('Creation date') }}
                      </th>
                      @can('manage-items', App\User::class)
                        <th class="text-right">
                          {{ __('Actions') }}
                        </th>
                      @endcan
                    </thead>
                    <tbody>
                      @foreach($items as $item)
                        <tr>
                          <td>
                            {{ $item->name }}
                          </td>
                          <td>
                            {{ $item->category->name }}
                          </td>
                          <td>
                            <img src="{{ $item->path() }}" alt="" style="max-width: 200px;">
                          </td>
                          <td>
                            @foreach ($item->tags as $tag)
                                <span class="badge badge-default" style="background-color:{{ $tag->color }}">{{ $tag->name }}</span>
                            @endforeach
                          </td>
                          <td>
                            {{ $item->created_at->format('Y-m-d') }}
                          </td>
                          @can('manage-items', App\User::class)
                            @if (auth()->user()->can('update', $item) || auth()->user()->can('delete', $item))
                              <td class="td-actions text-right">
                                <form action="{{ route('item.destroy', $item) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    
                                    @can('update', $item)
                                      <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('item.edit', $item) }}" data-original-title="" title="">
                                        <i class="material-icons">edit</i>
                                        <div class="ripple-container"></div>
                                      </a>
                                    @endcan
                                    @can('delete', $item)
                                      <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                          <i class="material-icons">close</i>
                                          <div class="ripple-container"></div>
                                      </button>
                                    @endcan
                                </form>
                              </td>
                            @endif
                          @endcan
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('js')
  <script>
    $(document).ready(function() {
      $('#datatables').fadeIn(1100);
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "All"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search items",
        },
        "columnDefs": [
          { "orderable": false, "targets": 5 },
        ],
      });
    });
  </script>
@endpush